services:
  mctd-k:
    build: .
    image: mctd-k 
    container_name: mctd-k-container
    working_dir: /workspace/mctd-k
    volumes:
      - ${HOME}/Workspace/mctd-k/outputs:/workspace/mctd-k/outputs
      - /home/frank/.wandb:/root/.wandb
      - ${HOME}/Workspace/mctd-k/configurations:/workspace/mctd-k/configurations
      - ${HOME}/Workspace/mctd-k/algorithms:/workspace/mctd-k/algorithms
    stdin_open: true
    tty: true
    shm_size: 8g
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - WANDB_API_KEY=${WANDB_API_KEY}
